package com.androiddevs.mvvmnewsapp.api

/**
 * class generated by JSON to Kotlin plugin
 */
data class Article(
    val author: String,
    val content: String,
    val description: String,
    val publishedAt: String,
    val source: Source,
    val title: String,
    val url: String,
    val urlToImage: String
)