package com.androiddevs.mvvmnewsapp.api

/**
 * class generated by JSON to Kotlin plugin
 */
data class ResponseApi(
    val articles: List<Article>,
    val status: String,
    val totalResults: Int
)