package com.androiddevs.mvvmnewsapp.models

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.androiddevs.mvvmnewsapp.models.Source
import java.io.Serializable

/**
 * class generated by JSON to Kotlin plugin
 */
@Entity( tableName = "articlesTable")
data class Article(

    @PrimaryKey(autoGenerate = true)
    val id:Int? = null,

    val author: String,
    val content: String,
    val description: String,
    val publishedAt: String,
    val source: Source,
    val title: String,
    val url: String,
    val urlToImage: String
) : Serializable