package com.androiddevs.mvvmnewsapp.models

import com.androiddevs.mvvmnewsapp.models.Article

/**
 * class generated by JSON to Kotlin plugin
 */
data class ResponseApi(
    val articles: List<Article>,
    val status: String,
    val totalResults: Int
)