package com.androiddevs.mvvmnewsapp.models

/**
 * class generated by JSON to Kotlin plugin
 */
data class ResponseApi(
    val articles: MutableList<Article>,
    val status: String,
    val totalResults: Int
)